apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

android {
    namespace "expo.modules.gcodeterminal"

    compileSdkVersion rootProject.ext.compileSdkVersion

    defaultConfig {
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
    }

    buildFeatures {
        buildConfig = true
    }
}

dependencies {
    implementation project(':expo-modules-core')
}
